### ISSUE TITLE
panic when sketching

### ISSUE THREAD

**Issue by jianshu93** [will-rowe/hulk#20]
Dear Will,

With the newest go version 1.16, I have the following error:

(base) [jianshu@c391 fasta]$ hulk sketch --fasta -f S_Baltica_OS675.fna -o ./S_Baltica_OS675.hulk.sketch
2021/12/26 18:24:00 this is hulk (version 1.0.0)
2021/12/26 18:24:00 please cite Rowe et al. 2019, doi: https://doi.org/10.1186/s40168-019-0653-2
2021/12/26 18:24:00 starting the sketch subcommand
2021/12/26 18:24:00 checking parameters...
2021/12/26 18:24:00 	mode: FASTA
2021/12/26 18:24:00 	no. processors: 1
2021/12/26 18:24:00 	minimizer k-mer size: 21
2021/12/26 18:24:00 	minimizer window size: 9
2021/12/26 18:24:00 	sketch size: 50
2021/12/26 18:24:00 	streaming: disabled
2021/12/26 18:24:00 	concept drift: disabled
2021/12/26 18:24:00 	number of bins in k-mer spectrum: 194481
2021/12/26 18:24:00 	adding KHF sketch: false
2021/12/26 18:24:00 	adding KMV sketch: false
2021/12/26 18:24:00 initialising sketching pipeline...
2021/12/26 18:24:00 	initialising the processes
2021/12/26 18:24:00 	connecting data streams
2021/12/26 18:24:00 	number of processes added to the sketching pipeline: 4
2021/12/26 18:24:00 	number of minions in the sketching pool: 1
2021/12/26 18:24:00 finding minimizers...
2021/12/26 18:24:00 generating final histosketch of k-mer spectra...
panic: send on closed channel

goroutine 8 [running]:
github.com/will-rowe/hulk/src/pipeline.(*Minion).Start.func1(0xc00010c0f0)
	/opt/conda/conda-bld/hulk_1563274818218/work/src/github.com/will-rowe/hulk/src/pipeline/minion.go:56 +0x5e
created by github.com/will-rowe/hulk/src/pipeline.(*Minion).Start
	/opt/conda/conda-bld/hulk_1563274818218/work/src/github.com/will-rowe/hulk/src/pipeline/minion.go:35 +0x3f

Is that because the new version of go?

Thanks,

Jianshu

**Comment by jianshu93** [comment]
[S_Baltica_OS675.fna.zip](https://github.com/will-rowe/hulk/files/7777813/S_Baltica_OS675.fna.zip)
